### ISSUE TITLE
kk命令怎么安装

### ISSUE THREAD

**Issue by sharewt** [chaseSpace/k8s-tutorial-cn#1]
# 删除calico pod，让其重启
kk delete pod -l k8s-app=calico-node -n kube-system

**Comment by sharewt** [comment]
[root@k8s-master ~]# kubeadm config images pull --image-repository registry.aliyuncs.com/google_containers
I0306 13:07:06.263170   15408 version.go:256] remote version is much newer: v1.29.2; falling back to: stable-1.27
W0306 13:07:07.378427   15408 images.go:80] could not find officially supported version of etcd for Kubernetes v1.27.11, falling back to the nearest etcd version (3.5.7-0)
failed to pull image "registry.aliyuncs.com/google_containers/kube-apiserver:v1.27.11": output: E0306 13:07:07.499704   15451 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/containerd/containerd.sock: connect: no such file or directory\"" image="registry.aliyuncs.com/google_containers/kube-apiserver:v1.27.11"
time="2024-03-06T13:07:07+08:00" level=fatal msg="pulling image: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/containerd/containerd.sock: connect: no such file or directory\""
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher

**Comment by chaseSpace** [comment]
kk是kubectl的缩写。

**Comment by chaseSpace** [comment]
在安装ohmyzsh的描述中有关于设置`kk`别名的步骤：
https://github.com/chaseSpace/k8s-tutorial-cn/blob/main/doc_install_ohmyzsh.md
