### ISSUE TITLE
指令问题

### ISSUE THREAD

**Issue by v04007** [chaseSpace/k8s-tutorial-cn#2]
4.9 更新的暂停与恢复 中 `kk set image deploy hellok8s-go-http=leigg/hellok8s:v2`  执行失败

**Comment by chaseSpace** [comment]
提供执行现场截图，以及相关日志，例如`kk describe po $POD_ID` 的Events部分

**Comment by chaseSpace** [comment]
如无后续，issue将在两天后关闭。

**Comment by chaseSpace** [comment]
感谢反馈，第一处应该是一个命令错误，你切换的是正确的；第二处命令中的N是个代号，执行时需要替换为具体的修订号（已追加说明）。
